import sys
from datetime import datetime, timezone
from textwrap import dedent


def disclaimer(comment_introducer=None):
    c = comment_introducer or "//"
    return dedent(
        f"""
        {c}
        {c} This file was automatically generated by
        {c} {" ".join(sys.argv)}
        {c} At {datetime.now(timezone.utc)}
        {c} DO NOT MODIFY THIS FILE MANUALLY
        {c}"""[1:]
    )
