
== The `flow` library

See code at
https://github.com/intel/compile-time-init-build/tree/main/include/flow.
Everything in the flow library is in the `flow` namespace.

A flow is a series of actions to be executed in order based on their
dependencies. The flow library was originally designed to be used for power
flows, moving from one power state to another. A flow can also be used as a
generic extension point to register callbacks at compile-time. A flow implements
the _cib_ `service` pattern.

=== Example

Flow extension points are declared by deriving from `flow::service`.

[source,cpp]
----
struct MorningRoutine : public flow::service<"MorningRoutine"> {};
----

The builder is used during the `constexpr` init() phase to define and extend the
flow. Actions to be added to the flow are declared and defined as `constexpr`
constants.

[source,cpp]
----
namespace food {
  constexpr static auto MAKE_COFFEE = flow::action<"MAKE_COFFEE">([] {
    coffee_maker.start(ground_coffee.take(100_grams), water.take(16_ounces));
  });

  constexpr static auto DRINK_COFFEE = flow::action<"DRINK_COFFEE">([] {
    // gulp
  });
}
----

Actions are added to the flow inside a component's `cib::config`.

[source,cpp]
----
struct morning {
  constexpr auto config = cib::config(
    cib::extend<MorningRoutine>(
        *WAKE_UP >>
        *selfcare::SHOWER >>
        *selfcare::GET_DRESSED >>
        *food::MAKE_COFFEE >>
        *food::DRINK_COFFEE));
};
----

The `>>` operator is used to create a dependency between two actions. For
example `WAKE_UP >> SHOWER` means you need to wake up first before you can take
a shower. The flow library will order actions in a flow to respect these
dependencies. The actions will be executed in an order that respects all given
dependencies.

The `\*` operator is used to explicitly add an action to the
flow. Without the `*` operator an action is just a reference.
A compile-time error will be triggered if an action is referenced without ever
being explicitly added to the flow. If an action is added under a constexpr
or runtime conditional, and the conditional is false, then it is as if the
action was never added at all.

The behavior of the `*` operator ensures that merely referencing an 
action to create an ordering dependency doesn't unintentionally add the action
to the flow.

If we only use the `morning` component in our project, the `MorningRoutine` flow
graph would look like the following:

mermaid::morning_flow1.mmd[format="svg" config="mermaid.conf"]

The power of `flow` services comes when more than one component adds actions to
the flow. Flows can be extended by inserting additional actions with new
dependencies.

[source,cpp]
----
struct childcare {
  constexpr static auto PACK_SCHOOL_LUNCHES = flow::action<"PACK_SCHOOL_LUNCHES">([] {
    // ...
  });

  constexpr static auto SEND_KIDS_TO_SCHOOL = flow::action<"SEND_KIDS_TO_SCHOOL">([] {
    // ...
  });

  constexpr auto config = cib::config(
      cib::extend<MorningRoutine>(
          food::MAKE_COFFEE >>          // this step exists in the MorningRoutine flow
          *PACK_SCHOOL_LUNCHES >>       // new
          food::DRINK_COFFEE >>         // existing
          *food::MAKE_BREAKFAST >>      // new
          *food::EAT_BREAKFAST >>       // new
          *SEND_KIDS_TO_SCHOOL));       // new
};
----

The new steps are inserted into the existing `flow`​'s dependency graph:

mermaid::morning_flow2.mmd[format="svg" config="mermaid.conf"]

Multiple independent components can add actions to the same `flow`. This is the
power of `flow` services, they can be extended by multiple independent
components to create new functionality.

[source,cpp]
----
struct exercise {
  constexpr static auto RIDE_STATIONARY_BIKE = flow::action<"RIDE_STATIONARY_BIKE">([] {
    // ...
  });

  constexpr auto config = cib::config(
      cib::extend<MorningRoutine>(
          morning::WAKE_UP >>
          *RIDE_STATIONARY_BIKE >>
          selfcare::SHOWER));
};
----

The `MorningRoutine` `flow` now contains the functionality of three components,
all without the `MorningRoutine` source code having known about the new
functionality. We can mix and match new components without modifying the
original source code.

mermaid::morning_flow3.mmd[format="svg" config="mermaid.conf"]

The `cib` library will take care of initializing and building all services,
including `flow` services. For `flow`​s, this means the dependency graph will be
serialized into a sequence of actions at compile-time to be executed in order at
runtime.

[source]
----
MorningRoutine
 1. WAKE_UP
 2. exercise::RIDE_STATIONARY_BIKE
 3. selfcare::SHOWER
 4. selfcare::GET_DRESSED
 5. food::MAKE_COFFEE
 6. childcare::PACK_SCHOOL_LUNCHES
 7. food::DRINK_COFFEE
 8. food::MAKE_BREAKFAST
 9. food::EAT_BREAKFAST
10. childcare::SEND_KIDS_TO_SCHOOL
----

All of these components are composed in a project component and brought to life
with an instance of `cib::top`. We need to make sure our `flow`​s get executed at
the appropriate times, so our example has a `day_cycle` component that defines
the various extension points and ensures they get executed over and over in
`cib::top`​'s `MainLoop`.

[source,cpp]
----
// simple component for scheduling daily activities
struct day_cycle {
  constexpr static auto DAY_CYCLE = flow::action<"DAY_CYCLE">([] {
      flow::run<MorningRoutine>();
      flow::run<DaytimeRoutine>();
      flow::run<EveningRoutine>();
      wait_for_morning_time();
  });

  constexpr auto config = cib::config(
      cib::exports<
          MorningRoutine,
          DaytimeRoutine,
          EveningRoutine>,
      cib::extend<MainLoop>(
          DAY_CYCLE));
};

// bring together all the components for the project
struct my_life {
  constexpr auto config =
      cib::components<
          day_cycle,
          morning,
          childcare,
          exercise>;
};

// use cib::top to create our nexus and main function
cib::top<my_life> top{};

int main() {
  top.main();
}
----

=== API

==== `service`

Defines a new `flow` service. If the `flow::service` template is given a name
then it will automatically log the beginning and end of the `flow` as well as
all actions.

[source,cpp]
----
// declare a flow without logging
struct MyFlow : public flow::service<> {};

// declare a flow with automatic logging enabled
struct MyFlowWithLogging : public flow::service<"MyFlowWithLogging"> {};
----

==== `action`

Defines a new `flow` action. All `flow` actions are created with a name and a
lambda expression. `flow` action and milestone names must be unique within a
`flow`. The same action can be used in multiple flows. Actions cannot be added
to a flow more than once, but can be referenced by other actions when adding
dependencies.

[source,cpp]
----
constexpr static auto MY_ACTION = flow::action<"MY_ACTION_NAME">([] {
  // do useful stuff
});
----

==== `milestone`

Defines a new `flow` milestone. Milestones are used only for their name: they
perform no action. They are used as points within a `flow` which other actions
may base their dependencies on.

[source,cpp]
----
constexpr static auto MY_MILESTONE = flow::milestone<"MY_MILESTONE_NAME">();
----

==== `run`

Runs a flow, executing all its actions in the prescribed order.

[source,cpp]
----
flow::run<MyFlow>();
----

==== `operator>>`

Creates a dependency between two or more actions and/or milestones. Must be
passed into the `cib::extend` configuration method for it to have an effect. Can
be chained together to create a sequence of dependent actions.

[source,cpp]
----
namespace example_component {
  constexpr auto config = cib::config(
      cib::extend<MyFlow>(
          // SOME_ACTION must execute before SOME_OTHER_ACTION
          SOME_ACTION >> SOME_OTHER_ACTION));
}
----

==== `operator&&`

Allows two or more actions and/or milestones to run in parallel without any
ordering requirement between them. If there is no dependency between two or more
actions, this is the preferred way of adding them to a `flow`. Other components
will then be able to insert actions in between if needed.

[source,cpp]
----
namespace example_component {
  constexpr auto config = cib::config(
      cib::extend<MyFlow>(
          // no order requirement between these actions
          *SOME_ACTION && *SOME_OTHER_ACTION));
}
----

==== `operator*`

Explicitly add an action to the flow. Actions used in flow extensions without
the `\*` will be treated as references only and will not be added to the
flow at that location. It is a compilation error if an action is not added 
with a `*` in exactly one location in the overall config.

Actions can be added and ordered all at once:

[source,cpp]
----
namespace example_component {
  constexpr auto config = cib::config(
      cib::extend<MyFlow>(
          // Add both actions and create an ordering between them.
          *SOME_ACTION >> *SOME_OTHER_ACTION));
}
----

Actions can also be added and ordered seperately:

[source,cpp]
----
namespace other_component {
  constexpr auto INIT_SOMETHING = ...

  constexpr auto config = cib::config(
      cib::extend<MyFlow>(*INIT_SOMETHING));
}

namespace example_component {
  constexpr auto DO_A_THING = ...

  constexpr auto config = cib::config(
      cib::extend<MyFlow>(
          other_component::INIT_SOMETHING >> 
          *DO_A_THING));
}
----

=== Alternative flow builders

The default flow service uses a graph builder that outputs the flow steps as an
array of function pointers. Traversing the array and calling those functions
ensures the correct relative ordering of flow steps in the graph, and this is
what happens by default when we run the flow.

[source,cpp]
----
// the default flow builder and service
template <stdx::ct_string Name = "">
using builder = flow::graph<Name, flow::graph_builder<impl>>;

template <stdx::ct_string Name = "">
struct service {
  using builder_t = builder<Name>;
  using interface_t = flow::FunctionPtr;
};

// declare a flow service
struct MorningRoutine : public service<"MorningRoutine"> {};

// add steps, etc, then at runtime, run the flow:
nexus.service<"MorningRoutine">();
----

Here `graph_builder` is the type that renders the flow description into the
array of function pointers, and `flow::FunctionPtr` is the type-erased interface
(here a function taking no arguments and returning `void`) that is called to run
a flow.

But given a flow, other renderings are possible.

[source,cpp]
----
// a flow builder and service that produces a graphviz rendering
template <stdx::ct_string Name = "">
using viz_builder = flow::graph<Name, flow::graphviz_builder>;

template <stdx::ct_string Name = "">
struct viz_service {
  using builder_t = builder<Name>;
  using interface_t = flow::VizFunctionPtr;
};
----

Here, `viz_service` will produce a graphviz rendering of a flow using the
`graphviz_builder`. `flow::VizFunctionPtr` is the type-erased interface once
more, and it is defined to take no arguments and return a `std::string`. When we "run"
the flow, we get the graphviz rendering.

[source,cpp]
----
// instead of the default flow::service, use the viz_service
struct MorningRoutine : public viz_service<"MorningRoutine"> {};

// add steps, etc, as before
// this time, when we "run" the flow, we get a string representing the graphviz rendering
auto graphviz_str = nexus.service<"MorningRoutine">();
----

`graphviz_builder` is available as a debugging aid. But in general, having the
flow rendering separate from the flow definition enables any kind of rendering
with correponding runtime behaviour.
