== Introduction

`cib` is a C++ header-only library for building embedded firmware with reusable
components. It implements the compile-time initialization and build pattern.
Instead of initializing components and registering callbacks at runtime, this
process is executed at compile-time using constexpr or consteval functions.

This documentation is a work in progress. See also the
https://github.com/intel/compile-time-init-build/blob/main/README.md[`README`]
file for information.

=== Compiler and C++ version support

The following compilers are supported:

* clang 14 thru 17
* GCC 12 thru 13

C++20 is required.

An older version of `cib` (not covered by this documentation) that uses C++17 is
tagged at https://github.com/intel/compile-time-init-build/tree/v1.7.0[v1.7.0].
It is tested with:

* clang 9 thru 15
* GCC 9 thru 12

=== Dependencies

This repository uses https://github.com/cpm-cmake/CPM.cmake[CPM] and a
https://github.com/intel/cicd-repo-infrastructure[common CI/CD infrastructure].

The library dependencies are:

- https://github.com/boostorg/mp11[Boost.MP11]
- https://github.com/intel/cpp-std-extensions[C++ std extensions (`stdx`)]
- https://github.com/intel/cpp-baremetal-concurrency[Baremetal Concurrency (`conc`)]
- https://github.com/intel/cpp-senders-and-receivers[Baremetal Senders and Receivers (`async`)]
- https://github.com/fmtlib/fmt[fmt]

=== Functionality

_cib_ contains several parts that work together:

- xref:flow.adoc#_the_flow_library[`flow`]
- xref:logging.adoc#_the_logging_library[`logging`]
- xref:interrupt.adoc#_the_interrupt_library[`interrupt`]
- xref:match.adoc#_the_match_library[`match`]
- xref:message.adoc#_the_message_library[`message`]

=== Sub-library DAG

Various sub-libraries within CIB form a dependency graph. `cib` is an omnibus
library that contains all the functionality.

[mermaid, format="svg"]
----
flowchart BT
  nexus(cib_nexus)
  log(cib_log)
  match(cib_match)
  lookup(cib_lookup)

  flow(cib_flow) --> nexus
  flow --> log

  log_fmt(cib_log_fmt) --> log
  msg(cib_msg) --> log & match
  msg --> lookup

  log_binary(cib_log_binary) --> msg
  seq(cib_seq) --> flow

  interrupt(cib_interrupt)
  cib --> seq & log_fmt & log_binary & interrupt
----
