== Introduction

`cib` is a C++ header-only library for building embedded firmware with reusable
components. It implements the compile-time initialization and build pattern.
Instead of initializing components and registering callbacks at runtime, this
process is executed at compile-time using constexpr or consteval functions.

This documentation is a work in progress. See also the
https://github.com/intel/compile-time-init-build/blob/main/README.md[`README`]
file for information.

=== Compiler and C++ version support

The following compilers are supported:

* clang 14 thru 21
* GCC 12 thru 14

C++20 is required.

An older version of `cib` (not covered by this documentation) that uses C++17 is
tagged at https://github.com/intel/compile-time-init-build/tree/v1.7.0[v1.7.0].
It is tested with:

* clang 9 thru 15
* GCC 9 thru 12

=== Dependencies

This repository uses https://github.com/cpm-cmake/CPM.cmake[CPM] and a
https://github.com/intel/cicd-repo-infrastructure[common CI/CD infrastructure].

The library dependencies are:

- https://github.com/boostorg/mp11[Boost.MP11]
- https://github.com/intel/cpp-std-extensions[C++ std extensions (`stdx`)]
- https://github.com/intel/cpp-baremetal-concurrency[Baremetal Concurrency (`conc`)]
- https://github.com/intel/cpp-senders-and-receivers[Baremetal Senders and Receivers (`async`)]
- https://github.com/fmtlib/fmt[fmtlib]

NOTE: `fmtlib` is used at compile-time only; there is no runtime formatting in `cib`.

=== Functionality

_cib_ contains several parts that work together:

- xref:flow.adoc#_the_flow_library[`flow`]
- xref:logging.adoc#_the_logging_library[`logging`]
- xref:interrupt.adoc#_the_interrupt_library[`interrupt`]
- xref:match.adoc#_the_match_library[`match`]
- xref:message.adoc#_the_message_library[`message`]

=== Sub-library DAG

Various sub-libraries within CIB form a dependency graph. `cib` is an omnibus
library that contains all the functionality.

mermaid::library_deps.mmd[format="svg" config="mermaid.conf"]

=== Getting Started

`cib` is a header-only library, so you can get started by cloning the repository
(or bringing it in as a submodule) and adding the include directory to your
build target. Depending on which part(s) of `cib` you are using, you may also
need to pull in the dependencies.

Alternatively, consuming `cib` with https://github.com/cpm-cmake/CPM.cmake[CPM]
can be a couple of lines:

[source,cmake]
----
cpmaddpackage("gh:intel/compile-time-init-build#1abcdef")

target_link_libraries(my_project PUBLIC cib)
----

Where `1abcdef` is the git hash. You can also use any of the sub-libraries (for
example, `cib_log_binary`) in this way.
