
== The `logging` library

See code at
https://github.com/intel/compile-time-init-build/tree/main/include/log.
Everything in the logging library is in the `logging` namespace, although most
user code will use macros.

Logging in _cib_ is in two parts:

- the interface, in https://github.com/intel/compile-time-init-build/tree/main/include/log/log.hpp[log.hpp]
- an implementation, which can be specified at the top level

Three possible logger implementations are provided:

- one using fmt in https://github.com/intel/compile-time-init-build/tree/main/include/log/fmt/logger.hpp[fmt/logger.hpp]
- one using binary encoding in https://github.com/intel/compile-time-init-build/tree/main/include/log/catalog/encoder.hpp[catalog/encoder.hpp], using the https://www.mipi.org/specifications/sys-t[MIPI Sys-T spec] by default
- the default implementation: the null logger which accepts everything, but never produces output

=== Log levels

_cib_ offers 6 well-known and 2 user-defined log levels, according to the https://www.mipi.org/specifications/sys-t[MIPI Sys-T spec].

[source,cpp]
----
enum struct level {
    MAX = 0,
    FATAL = 1,
    ERROR = 2,
    WARN = 3,
    INFO = 4,
    USER1 = 5,
    USER2 = 6,
    TRACE = 7
};
----

=== Log macros

_cib_ log macros follow the log levels:

[source,cpp]
----
CIB_TRACE(...);
CIB_INFO(...);
CIB_WARN(...);
CIB_ERROR(...);
CIB_FATAL(...);
----

`CIB_FATAL` causes a call to
https://intel.github.io/cpp-std-extensions/#_panic_hpp[`stdx::panic`], and
`CIB_ASSERT(expression)` is equivalent to `CIB_FATAL` in the case where the
expression evaluates to `false`.

=== Selecting a logger

In order to use logging in a header, it suffices only to include
https://github.com/intel/compile-time-init-build/tree/main/include/log/log.hpp[log.hpp]
and use the macros. Header-only clients of logging do not need to know the
implementation selected.

To use logging in a translation unit, specialize the `logging::config` variable
template. Left unspecialized, the null logger will be used.

[source,cpp]
----
// use fmt logging to std::cout
template <>
inline auto logging::config<> = logging::fmt::config{std::ostream_iterator<char>{std::cout}};
----

The provided `fmt` implementation can output to multiple destinations by constructing
`logging::fmt::config` with multiple `ostream` iterators.

CAUTION: Be sure that each translation unit sees the same specialization of
`logging::config`! Otherwise you will have an https://en.cppreference.com/w/cpp/language/definition[ODR violation].

=== Implementing a logger

Each logging implementation (configuration) provides a customization point: a
`logger` object, which must implement `log`. Therefore providing a custom
implementation is a matter of defining this structure appropriately.

[source,cpp]
----
struct my_logger_config {
  struct {
    template <typename Env, typename File, typename Line, typename Msg>
    auto log(File, Line, Msg const &msg) -> void {
      // log according to my mechanism
    }
  } logger;
};
----

Notice that the first template parameters to log is the
xref:logging.adoc#_logging_environments[environment].

The first two runtime parameters receive preprocessor `\_​_FILE_​\_` and `__LINE_​_` values
respectively. The `msg` argument is a structure containing a
xref:sc.adoc#_formatting_strings[compile-time format string] and runtime
arguments to be interpolated into it. It supports an `apply` function, so one
way to implement `log` is:

[source,cpp]
----
struct my_logger_config {
  struct {
    template <typename Env, typename File, typename Line, typename Msg>
    auto log(File, Line, Msg const &msg) -> void {
      msg.apply([] <typename Str> (Str, auto const&... args) {
        std::print(Str::value, args...);
      });
    }
  } logger;
};
----

NOTE: `Str::value` here is a compile-time `std::string_view`.

To use the custom implementation, as with any built-in choice of logger,
specialize `logging::config`:

[source,cpp]
----
template <>
inline auto logging::config<> = my_logger_config{};
----

=== Flavored logs

There is not always just one logging backend in an application. For example, you
might want regular logs and secure logs. Providing more backends is possible by specializing
`logging::config` with custom types.

[source,cpp]
----
struct secure_tag;

template <>
inline auto logging::config<secure_tag> = my_logger_config{};
----

And this backend can be most easily used by defining macros in terms of the
`CIB_LOG` macro:

[source,cpp]
----
#define SECURE_TRACE(...) CIB_LOG(secure_tag, logging::level::TRACE, __VA_ARGS__)
#define SECURE_INFO(...) CIB_LOG(secure_tag, logging::level::INFO, __VA_ARGS__)
// etc
----

=== Modules

It can be helpful to scope or filter log messages by associating them with
module IDs. Several logging backends have support for this idea. Tagging every
log call site gets verbose and error-prone, so instead the approach taken by
_cib_ is to override log modules by using `CIB_LOG_MODULE` declarations at
namespace, class or function scope.

[source,cpp]
----
auto global_f() {
  CIB_INFO("This log uses the default module ID");
}

namespace my_ns {
CIB_LOG_MODULE("my_ns");
CIB_INFO("This log uses my_ns as its module ID");

struct my_struct {
  CIB_LOG_MODULE("my_struct");

  auto f() {
    CIB_INFO("This log uses my_struct as its module ID");
  }

  auto g() {
    CIB_LOG_MODULE("g");
    CIB_INFO("This log uses g as its module ID");
  }
};
}
----

=== String data

On a constrained system, space for text can be at a premium. The `sc` library
and the MIPI Sys-T logger combine to
xref:sc.adoc#_efficient_logging_with_mipi_sys_t[solve this problem].

=== Version logging

To provide version information in a log, specialize the `version::config`
variable template. The configuration should provide a `build_id` and a
`version_string`.

[source,cpp]
----
struct my_version_config {
    constexpr static auto build_id = std::uint64_t{1234};
    constexpr static auto version_string = stdx::ct_string{"version"};
};

template <> inline auto version::config<> = my_version_config{};
----

Then use `CIB_LOG_VERSION()` to log the version. If the logging config provides
a `log_version` function, that will be used. Otherwise a text string will be
logged.

[source,cpp]
----
struct my_logger_config {
  struct {
    template <auto Version, stdx::ct_string S = ""> auto log_version() -> void {
      // log the build version according to my mechanism
    }
  } logger;
};
template <>
inline auto logging::config<> = my_logger_config{};

CIB_LOG_VERSION(); // calls my_logger_config::log_version
----

The easiest way to flavor the version logging is to define a macro in terms of
`CIB_LOG_V`:

[source,cpp]
----
#define LOG_SECURE_VERSION(...) CIB_LOG_V(secure_tag)
----

=== Logging environments

The logging environment is a compile-time map from types to values that allows a
logger to look up various parameters, including the module ID, the log level,
and the flavor. It can also be used to provide user-defined values to be
interpreted by a logging backend.

The macros that implement logging with various levels, modules, and flavors
are implemented as environment declarations, for example:
[source,cpp]
----
CIB_LOG_ENV(logging::get_level, logging::level::TRACE);
CIB_LOG("Hello");  // logs with TRACE level
----
or:
[source,cpp]
----
CIB_LOG_ENV(logging::get_flavor, secure_tag);
CIB_TRACE("Hello");  // logs with secure back end
----
A temporary override of values can be done with `CIB_WITH_LOG_ENV`:
[source,cpp]
----
CIB_WITH LOG_ENV(logging::get_level, logging::level::TRACE,
                 logging::get_flavor, secure_tag) {
  CIB_LOG("Hello");  // logs a TRACE with secure back end
}
----

To interrogate the environment from a custom logger, use the appropriate query
on the environment.
[source,cpp]
----
struct my_logger_config {
  struct {
    template <typename Env, typename File, typename Line, typename Msg>
    auto log(File, Line, Msg const &msg) -> void {
      constexpr auto level = get_level(Env{}).value;
      // ...
    }
  } logger;
};
----
