
== The `sc` (string constant) library

See code at
https://github.com/intel/compile-time-init-build/tree/main/include/sc.
Everything in the sc library is in the `sc` namespace.

=== String constants

An `sc::string_constant` is a compile-time string in the same way that
`std::integral_constant` is a compile-time integral value: it carries the string
in the type as a pack of `char`​s.

[source,cpp]
----
template <typename Char, Char... chars> struct string_constant;
----

The easiest way to create a `string_constant` is using a user-defined literal:

[source,cpp]
----
constexpr auto hello_world = "Hello, world!"_sc;

// the string data itself is available as a compile-time std::string_view
using std::string_view_literals;
static_assert(decltype(hello_world)::value == "Hello, world!"sv);
----

`string_constant` specializations can be compared (even though they are
different types), and `operator+` is defined for concatenation.

[source,cpp]
----
// comparisons use lexicographical ordering
static_assert("Alice"_sc < "Bob"_sc);

static_assert("Hello,"_sc + " World!"_sc == "Hello, World!"_sc);
----

=== Efficient logging with MIPI Sys-T

The reason `string_constant` exists is for efficient logging. On a constrained
system, space for text can be limited-to-nonexistent. `string_constant`
interacts with the
https://github.com/intel/compile-time-init-build/tree/main/include/log/catalog/mipi_encoder.hpp[MIPI
Sys-T logging config] to solve this problem.

- First, each `string_constant` contains string character data in its type.
- The MIPI logger calls the function template specialization
  https://github.com/intel/compile-time-init-build/blob/main/include/log/catalog/catalog.hpp[`catalog`]
  to get the catalog ID corresponding to each `string_constant`.

But: the `catalog` function template is just that -- only a template -- to
begin with. It is specialized as follows:

- The application is built as a library.
- Running `nm` on that library reveals missing symbols: precisely the function
  specializations that are required for all the instances of `string_constant`.
- Those symbols are used to generate the template specializations in another
  file, which itself is compiled into a library.
- String data is recovered from the symbol types and used to generate the
  catalog collateral in XML and/or JSON format.
- Link-time optimization inlines the `catalog` function template
  specializations, each of which is a one-line function that returns a
  catalog ID.

Thus no string data exists in the executable, but the correct catalog IDs are
used in logging, and the remote log handler can reconstitute the actual strings.
The XML and JSON collateral also contains information about any runtime
arguments that need to be interpolated into the string and whose values are sent
by the MIPI Sys-T logger after the catalog ID.

==== Tooling support

The process of generating log strings from the type information revealed by
missing symbols is automated by a
https://github.com/intel/compile-time-init-build/blob/main/tools/gen_str_catalog.py[python
script] provided and by a
https://github.com/intel/compile-time-init-build/blob/main/cmake/string_catalog.cmake[CMake
wrapper function (`gen_str_catalog`)] that drives the process. See
https://github.com/intel/compile-time-init-build/blob/main/test/CMakeLists.txt[the
test] that exercises that functionality for an example.

NOTE: This process assigns IDs to both strings and
xref:logging.adoc#_modules[log modules]. `catalog` is specialized for catalog
IDs; `module` is specialized for module IDs.

=== Formatting strings

`string_constants` are formatted at compile time using
https://github.com/fmtlib/fmt[fmt]. Helpers are available for compile-time
formatting of enum values, type names or integral constants:

[source,cpp]
----
// string constants themselves are interpolated at compile time
sc::format("My name is {}"_sc, "Alice"_sc); // "My name is Alice"

// enum values are interpolated at compile time
sc::format("The max log level is {}"_sc, sc::enum_<logging::MAX>); // "The max log level is MAX"

// integral constants likewise
sc::format("{} is a taxicab number"_sc, std::integral_constant<int, 1729>{}); // "1729 is a taxicab number"

// and names of types
sc::format("When in doubt, do as the {}s do"_sc, sc::type_<int>); // "When in doubt, do as the ints do"
----

When using _cib_ xref:logging.adoc#_log_macros[log macros], any arguments that
can be formatted at compile-time are automatically interpolated into the
`string_constant`, leaving the rest as dynamic runtime arguments to
xref:logging.adoc#_implementing_a_logger[`log`].

[source,cpp]
----
// here, 42 is interpolated at compile time
// (sc::int_<42> is an integral_constant)
sc::format("The answer is {}"_sc, sc::int_<42>);

// here, 42 is a runtime argument
// (because C++ doesn't have constexpr function parameters)
constexpr auto answer = 42;
sc::format("The answer is {}"_sc, answer);
----
